remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-gb"
title                    : "Harbour22"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Chris"
description              : "A safe port on the web"
url                      : https://thoughts.harbour22.uk
repository               : harbour22/harbour22.github.io
masthead_title           : Harbour22
words_per_minute         : 200
comments:
  provider               : false
atom_feed:
  path                   : 
search                   : true
search_full_content      : false
search_provider          : lunr

# Social Sharing
twitter:
  username               : harbour22
og_image                 : # Open Graph/Twitter default site image

# Analytics
analytics:
  provider               : google
  google:
    tracking_id          : UA-110146917-1

# Site Author
author:
  name             : "Chris"
  avatar           : "/assets/images/avatar.jpg"
  bio              : "Software Engineer"
  location         : "London, UK"
  #email            : thenarrator@harbour22.uk
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/harbour22/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/harbour22uk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/chrismathie"      

# Site Footer
footer:
  links:

# Reading Files
include:
  - .htaccess
  - _posts
  - _pages
exclude:
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  mavicair:
    output: true
    permalink: /:collection/:path/
    order: 
      - mavicair.md
  docs:
    output: true
    permalink: /:collection/:path/      

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true      
  # _portfolio
  - scope:
      path: ""
      type: mavicair
    values:
      layout: single
      author_profile: false
      share: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"      

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones